
-- Auto-generated by JNKIE Discord Bot
-- Service: Test
-- Generated for: inkwell1

loadstring(game:HttpGet("https://api.jnkie.com/api/v1/luascripts/public/a2dcafb01696647bc5eea80a6d43e201faa0029c34728f75bcc057a444904ec1/download"))()
