
-- Auto-generated by JNKIE Discord Bot
-- Service: Test
-- Generated for: inkwell1

getgenv().SCRIPT_KEY = "74d00b53-90db-4658-b8e0-bb4bd5884d9b"

loadstring(game:HttpGet("https://api.jnkie.com/api/v1/luascripts/public/8eef94199d5fda6409147795d93e7f4b924b765800ea1c5642f8311aea0e683a/download"))()
